const SUPABASE_URL='https://nrnrmbjrczmzkgimxdun.supabase.co';
const SUPABASE_KEY='sb_publishable_Lrb0SZIai9FwSYy0oDbnzg_vZ4BTakA';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const views=['authView','adminView','homeView','mapView','lessonView'];
const letters=[['اَ','A'],['بَ','BA'],['تَ','TA'],['ثَ','THA'],['جَ','JA'],['حَ','HA'],['خَ','KHA'],['دَ','DA'],['ذَ','DZA'],['رَ','RA'],['زَ','ZA'],['سَ','SA'],['شَ','SYA'],['صَ','SO'],['ضَ','DHO'],['طَ','TO'],['ظَ','ZHO'],['عَ','A'],['غَ','GHO'],['فَ','FA'],['قَ','QO'],['كَ','KA'],['لَ','LA'],['مَ','MA'],['نَ','NA'],['هَ','HA'],['وَ','WA'],['يَ','YA']];
const pageSets=Array.from({length:32},(_,i)=>Array.from({length:4},(_,j)=>letters[Math.min(i+j,letters.length-1)]));
let user=null,profile=null,adminToken=sessionStorage.getItem('iqraAdminToken')||'',progress={unlocked:1,completed_pages:[],stars:0},currentPage=1,step=0,testIndex=0,testScore=0;
function show(id){views.forEach(v=>$(v).classList.add('hidden'));$(id).classList.remove('hidden')}
function setMsg(id,text,ok=false){$(id).textContent=text;$(id).style.color=ok?'#15803d':'#b91c1c'}
async function adminLogin(e){e.preventDefault();setMsg('adminLoginMsg','Memproses...');const username=$('adminUsername').value.trim(),password=$('adminPassword').value;const {data,error}=await db.rpc('iqra_admin_login',{p_username:username,p_password:password});if(error||!data?.length)return setMsg('adminLoginMsg','Username atau password admin tidak betul.');adminToken=data[0].token;sessionStorage.setItem('iqraAdminToken',adminToken);$('displayName').textContent=data[0].display_name;$('userBar').classList.remove('hidden');setMsg('adminLoginMsg','');await loadAdminDashboard()}
async function loadAdminDashboard(){if(!adminToken)return show('authView');const [{data:summary,error:se},{data:students,error:te}]=await Promise.all([db.rpc('iqra_admin_summary',{p_token:adminToken}),db.rpc('iqra_admin_students',{p_token:adminToken})]);if(se||te){sessionStorage.removeItem('iqraAdminToken');adminToken='';return show('authView')}$('adminUsers').textContent=summary.users||0;$('adminPages').textContent=summary.completed_pages||0;$('adminStars').textContent=summary.stars||0;$('adminActive').textContent=summary.active_progress||0;$('adminStudentRows').innerHTML=(students||[]).map(s=>`<tr><td>${escapeHtml(s.display_name||'-')}</td><td>H${s.unlocked||1}/32</td><td>${s.completed_count||0}</td><td>${s.stars||0}</td><td>${s.updated_at?new Date(s.updated_at).toLocaleString('ms-MY'):'-'}</td></tr>`).join('')||'<tr><td colspan="5">Belum ada pengguna berdaftar.</td></tr>';show('adminView')}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadAccount(){if(!user)return;const [{data:p,error:pe},{data:g,error:ge}]=await Promise.all([db.from('iqra_profiles').select('*').eq('id',user.id).single(),db.from('iqra_progress').select('*').eq('user_id',user.id).single()]);if(pe||ge){console.error(pe||ge);return}profile=p;progress=g;$('displayName').textContent=profile.display_name;$('welcomeName').textContent=profile.display_name;$('userBar').classList.remove('hidden');renderStats();show('homeView')}
function renderStats(){$('starCount').textContent=progress.stars||0;$('doneCount').textContent=(progress.completed_pages||[]).length;$('unlockCount').textContent=progress.unlocked||1;$('mainProgress').style.width=((progress.completed_pages||[]).length/32*100)+'%'}
async function register(e){e.preventDefault();setMsg('registerMsg','Mendaftar...');const name=$('registerName').value.trim(),email=$('registerEmail').value.trim(),password=$('registerPassword').value;const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)return setMsg('registerMsg',error.message);if(data.session){user=data.user;await loadAccount();setMsg('registerMsg','Berjaya didaftarkan.',true)}else setMsg('registerMsg','Pendaftaran berjaya. Semak email untuk pengesahan jika diminta.',true)}
async function login(e){e.preventDefault();setMsg('loginMsg','Memproses...');const email=$('loginEmail').value.trim(),password=$('loginPassword').value;const {data,error}=await db.auth.signInWithPassword({email,password});if(error)return setMsg('loginMsg','Email atau kata laluan tidak betul.');user=data.user;setMsg('loginMsg','');await loadAccount()}
async function logout(){if(adminToken){await db.rpc('iqra_admin_logout',{p_token:adminToken});sessionStorage.removeItem('iqraAdminToken');adminToken=''}if(user)await db.auth.signOut();user=profile=null;progress={unlocked:1,completed_pages:[],stars:0};$('userBar').classList.add('hidden');$('adminPassword').value='';show('authView')}
function openMap(){show('mapView');const grid=$('pageGrid');grid.innerHTML='';for(let n=1;n<=32;n++){const b=document.createElement('button');const locked=n>progress.unlocked,done=(progress.completed_pages||[]).includes(n);b.className='page-btn'+(locked?' locked':'')+(done?' done':'');b.disabled=locked;b.innerHTML=(locked?'🔒 ':'')+'H'+n+(done?'<br>⭐':'');b.onclick=()=>startPage(n);grid.appendChild(b)}}
function startPage(n){currentPage=n;step=0;testIndex=0;testScore=0;show('lessonView');renderStep()}
function renderStep(){const set=pageSets[currentPage-1],focus=set[(currentPage-1)%4];const labels=['Belajar','Dengar','Ikut Baca','Latihan','Ujian'];$('stepBadge').textContent=(step+1)+' / 5 · '+labels[step];$('lessonTitle').textContent='Halaman '+currentPage;$('arabicFocus').textContent=focus[0];$('romanFocus').textContent=focus[1];$('letterStrip').innerHTML=set.map(x=>`<div class="letter-box">${x[0]}<br><small>${x[1]}</small></div>`).join('');$('lessonFeedback').textContent='';$('lessonFeedback').className='feedback';$('nextStepBtn').style.display='inline-block';if(step===0)$('lessonBody').innerHTML='<p class="muted">Kenali bentuk huruf dan bunyi pendeknya.</p>';else if(step===1)$('lessonBody').innerHTML='<button class="ghost" onclick="speakFocus()">🔊 Dengar Bunyi</button><p class="muted">Dengar beberapa kali.</p>';else if(step===2)$('lessonBody').innerHTML='<button class="ghost" onclick="speakFocus()">🎙️ Dengar & Ikut</button><p class="muted">Ikut sebut dengan bunyi pendek.</p>';else if(step===3)makeQuiz(false);else{testIndex=0;testScore=0;makeQuiz(true)}}
function speakFocus(){const focus=pageSets[currentPage-1][(currentPage-1)%4];if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(focus[1].toLowerCase());u.lang='ms-MY';u.rate=.62;speechSynthesis.cancel();speechSynthesis.speak(u)}
function makeQuiz(isTest){const set=pageSets[currentPage-1],target=isTest?set[testIndex%set.length]:set[(currentPage-1)%4];const pool=letters.filter(x=>x[0]!==target[0]).sort(()=>Math.random()-.5).slice(0,3);const opts=[target,...pool].sort(()=>Math.random()-.5);$('arabicFocus').textContent=target[0];$('romanFocus').textContent=isTest?'Pilih huruf yang betul':'Latihan';$('lessonBody').innerHTML='<div class="choice-grid">'+opts.map(x=>`<button class="choice" data-value="${x[0]}">${x[0]}</button>`).join('')+'</div>';$('nextStepBtn').style.display='none';document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(b,b.dataset.value,target[0],isTest))}
function answer(btn,val,target,isTest){document.querySelectorAll('.choice').forEach(b=>b.disabled=true);if(val===target){btn.classList.add('correct');$('lessonFeedback').textContent='✨ Betul!';$('lessonFeedback').className='feedback good';if(isTest)testScore++}else{btn.classList.add('wrong');$('lessonFeedback').textContent='💪 Cuba lagi.';$('lessonFeedback').className='feedback bad';document.querySelectorAll('.choice').forEach(b=>{if(b.dataset.value===target)b.classList.add('correct')})}setTimeout(()=>{if(isTest){testIndex++;if(testIndex<4)makeQuiz(true);else finishPage()}else $('nextStepBtn').style.display='inline-block'},650)}
function nextStep(){if(step<4){step++;renderStep()}else finishPage()}
async function finishPage(){const completed=[...(progress.completed_pages||[])];let gained=0;if(!completed.includes(currentPage)){completed.push(currentPage);gained=testScore>=3?3:testScore===2?2:1;progress={...progress,completed_pages:completed,unlocked:Math.max(progress.unlocked,Math.min(32,currentPage+1)),stars:(progress.stars||0)+gained,updated_at:new Date().toISOString()};const {error}=await db.from('iqra_progress').update({completed_pages:progress.completed_pages,unlocked:progress.unlocked,stars:progress.stars,updated_at:progress.updated_at}).eq('user_id',user.id);if(error){console.error(error);$('lessonFeedback').textContent='Progres gagal disimpan. Cuba lagi.';return}}renderStats();$('stepBadge').textContent='Selesai 🎉';$('lessonTitle').textContent='Tahniah! Halaman '+currentPage+' selesai';$('arabicFocus').textContent='⭐';$('romanFocus').textContent=(gained||'')+(gained?' bintang':'');$('letterStrip').innerHTML='';$('lessonBody').innerHTML='<p class="muted">Progres telah disimpan ke akaun anda.</p>'+(currentPage<32?`<button class="primary" onclick="startPage(${currentPage+1})">Halaman Seterusnya ➜</button>`:'<b>🏆 Iqra\' 1 selesai!</b>');$('nextStepBtn').style.display='none'}
$('adminLoginForm').addEventListener('submit',adminLogin);$('loginForm').addEventListener('submit',login);$('registerForm').addEventListener('submit',register);$('logoutBtn').onclick=logout;$('refreshAdminBtn').onclick=loadAdminDashboard;$('startLearningBtn').onclick=openMap;$('backMapBtn').onclick=openMap;$('nextStepBtn').onclick=nextStep;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
(async()=>{if(adminToken){$('displayName').textContent='Administrator';$('userBar').classList.remove('hidden');return loadAdminDashboard()}const {data}=await db.auth.getSession();user=data.session?.user||null;if(user)await loadAccount();else show('authView');db.auth.onAuthStateChange(async(_event,session)=>{if(session?.user&&!user){user=session.user;await loadAccount()}if(!session&&!adminToken){user=null}})})();